spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:p6spy:mysql://localhost:3306/elastic_job_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        slave_1:
          url: jdbc:p6spy:mysql://localhost:3306/tungee_bigdata?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  elasticsearch:
    rest:
      uris: http://localhost:9200
lex:
  a: lex1111


test:
  list: aaa,bbb,ccc

server:
  ssl:
    key-alias: tomcat
    key-store: classpath:tomcat.keystore
    key-store-password: 123456
    key-store-type: JKS